name: Build and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Run tests
      run: pytest

  build-macos:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=PasswordManager/resources/macos/logo.icns --name PasswordManager PasswordManager/main.py

    - name: Copy resources to build directory
      run: |
        mkdir -p dist/resources
        find PasswordManager/resources -maxdepth 1 -type f -exec cp {} dist/resources/ \;

    - name: Copy macOS resources
      run: |
        mkdir -p dist/resources/macos
        find PasswordManager/resources/macos -maxdepth 1 -type f -exec cp {} dist/resources/macos \;

    - name: Upload macOS build
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: dist/

  build-windows:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=PasswordManager/resources/windows/logo.ico --name PasswordManager PasswordManager/main.py

    - name: Copy resources to build directory
      run: |
        xcopy PasswordManager/resources/* dist/resources/ /Y /I /EXCLUDE:PasswordManager/resources/windows/;PasswordManager/resources/macos/

    - name: Copy Windows resources
      run: |
        xcopy PasswordManager/resources/windows/* dist/resources/windows/ /E /I /Y

    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/
