name: Build and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest

    - name: Run tests
      run: pytest

  build-macos:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=PasswordManager/resources/logo.icns --name PasswordManager PasswordManager/main.py

    - name: Copy resources to build directory
      run: |
        cp -r PasswordManager/resources dist/resources

    - name: Upload macOS build
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: dist/

  build-windows:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=PasswordManager/resources/logo.ico --name PasswordManager PasswordManager/main.py

    - name: Copy resources to build directory
      run: |
        robocopy PasswordManager\resources dist\resources /e /NFL /NDL /NJH /NJS

    - name: Upload Windows build
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: dist/
